prSections:
  - title: QuickAdd
    filters: is:open repo:chhoumann/quickadd
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: QuickAdd
    filters: is:open repo:chhoumann/quickadd
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
defaults:
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # whether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  :owner/:repo: ~/projects/:repo
  chhoumann/thesis-chemcam: ~/projects/p9
pager:
  diff: difft --color=always --syntax-highlight=on # or delta for example
confirmQuit: false # show prompt on quit or not

