#!/usr/bin/env bash
# Point ~/.config/zellij at this repo, with an OS-specific clipboard overlay.
#
# Linux: symlink config.kdl so edits go straight into git.
# macOS: write config.kdl + os.macos.kdl (pbcopy) because Zellij has no include.
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$DOTFILES_DIR/config/zellij"
DEST="$HOME/.config/zellij"

if [[ -L "$DEST" ]]; then
  rm "$DEST"
fi
mkdir -p "$DEST/themes"

shopt -s nullglob
for theme in "$SRC/themes"/*; do
  ln -sfn "$theme" "$DEST/themes/$(basename "$theme")"
done

os="$(uname -s)"
case "$os" in
  Darwin)
    tmp="$(mktemp)"
    {
      printf '%s\n' '// Generated by scripts/link-zellij-config.sh. Edit config.kdl and os.macos.kdl, then ./install.'
      cat "$SRC/config.kdl"
      printf '\n'
      cat "$SRC/os.macos.kdl"
    } >"$tmp"
    mv "$tmp" "$DEST/config.kdl"
    ;;
  *)
    ln -sfn "$SRC/config.kdl" "$DEST/config.kdl"
    ;;
esac
