gui:
  showFileIcons: true
  nerdFontsVersion: "3"
git:
    paging:
        # colorArg: always
        # pager: delta --dark --paging=never -s
        externalDiffCommand: difft --color=always --syntax-highlight=on 
customCommands:
    - key: "<c-r>"
      command: "gh pr create --fill --web"
      context: "global"
      loadingText: "Creating pull request on GitHub"
    - key: "C"
      command: "git cz"
      description: "commit with commitizen"
      context: "files"
      loadingText: "opening commitizen commit tool"
      subprocess: true
    - key: "<c-a>" # ctrl + a
      description: "Pick AI commit"
      command: 'echo "{{.Form.Msg}}" > .git/COMMIT_EDITMSG && vim .git/COMMIT_EDITMSG && [ -s .git/COMMIT_EDITMSG ] && git commit -F .git/COMMIT_EDITMSG || echo "Commit message is empty, commit aborted."'
      context: "files"
      subprocess: true
      prompts:
          - type: "menuFromCommand"
            title: "AI Commits"
            key: "Msg"
            command: "bunnai"
            filter: '^(?P<number>\d+)\.\s(?P<message>.+)$'
            valueFormat: "{{ .message }}"
            labelFormat: "{{ .number }}: {{ .message | green }}"
