model = "gpt-5.4"
model_reasoning_effort = "high"
approval_policy = "never"
sandbox_mode = "danger-full-access"

tool_output_token_limit = 25000
web_search_request = true
web_search = "live"

responses_websockets_v2 = true
service_tier = "fast"
personality = "pragmatic"

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.3-codex"
"gpt-5.3-codex" = "gpt-5.4"

# [mcp_servers.RepoPrompt]
# command = "/Users/christian/RepoPrompt/repoprompt_cli"
# enabled = true
# tool_timeout_sec = 10000.0

# [mcp_servers.XcodeBuildMCP]
# command = "npx"
# args = ["-y", "xcodebuildmcp@latest"]
# env = { "XCODEBUILDMCP_SENTRY_DISABLED" = "false" }
# tool_timeout_sec = 600

[features]
undo = true
fast_mode = true
unified_exec = true
shell_snapshot = true
steer = true
multi_agent = true
prevent_idle_sleep = true
js_repl = true
responses_websockets_v2 = true
runtime_metrics = true
skill_env_var_dependency_prompt = true

[tools]
view_image = true

[agents]
max_threads = 32

[mcp_servers.RepoPrompt]
command = "/Users/christian/RepoPrompt/repoprompt_cli"
enabled = false
tool_timeout_sec = 10000.0

[mcp_servers.ChromeDevTools]
command = "npx"
enabled = false
args = ["-y", "chrome-devtools-mcp@latest", "--autoConnect", "--channel=stable", "--no-usage-statistics"]
